const COMMON_TOKEN_MINT = {
    SOL: "So11111111111111111111111111111111111111112",
    USDC: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    USDT: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    BONK: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6v5B1pPB263",
    JUP: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN"
};

export const COMMON_SYMBOLS: Record<string, string> = {
    SOL: COMMON_TOKEN_MINT.SOL,
    WSOL: COMMON_TOKEN_MINT.SOL,
    USDC: COMMON_TOKEN_MINT.USDC,
    USDT: COMMON_TOKEN_MINT.USDT,
    BONK: COMMON_TOKEN_MINT.BONK,
    JUP: COMMON_TOKEN_MINT.JUP
};

export const COMMON_DECIMALS: Record<string, number> = {
    [COMMON_TOKEN_MINT.SOL]: 9,
    [COMMON_TOKEN_MINT.USDC]: 6,
    [COMMON_TOKEN_MINT.USDT]: 6,
    [COMMON_TOKEN_MINT.BONK]: 5,
    [COMMON_TOKEN_MINT.JUP]: 6
};

export { COMMON_TOKEN_MINT };
